// SPDX-License-Identifier: GPL-2.0
/*
 * Part 6: V4L2 Capture Device with Controls
 *
 * Copyright (c) 2024 TECH VEDA
 * Author: Raghu Bharadwaj
 *
 * Concepts introduced (over Part 5):
 *   - V4L2 Controls Framework (v4l2_ctrl_handler)
 *   - Hardware image-processing registers (BRIGHTNESS, HFLIP)
 *   - Writing control values to hardware for real-time effect
 *
 * Carries forward from Part 5:
 *   - Interrupt-driven frame completion
 *   - Hardware descriptor ring with OWN flag handshake
 *   - VB2 streaming, format negotiation
 *
 * NOT yet covered (see Part 7):
 *   - dma-buf export (EXPBUF)
 *
 * LOAD ORDER:
 *   sudo insmod ../hw/vcam_hw_platform.ko
 *   sudo insmod vcam_ctrl.ko
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/io.h>
#include <linux/videodev2.h>
#include <linux/interrupt.h>
#include <linux/workqueue.h>
#include <linux/slab.h>
#include <media/v4l2-device.h>
#include <media/v4l2-dev.h>
#include <media/v4l2-ioctl.h>
#include <media/v4l2-fh.h>
#include <media/v4l2-ctrls.h>
#include <media/videobuf2-v4l2.h>
#include <media/videobuf2-vmalloc.h>

#include "../hw/vcam_hw_interface.h"

#define DRV_NAME	"vcam_ctrl"
#define VCAM_RING_SIZE	8

struct vcam_buffer {
	struct vb2_v4l2_buffer vb;
	struct list_head       list;
};

struct vcam_device {
	struct v4l2_device       v4l2_dev;
	struct video_device      vdev;
	struct vb2_queue         queue;
	struct v4l2_pix_format   fmt;
	struct mutex             lock;
	struct platform_device  *pdev;

	/* Hardware interface */
	void __iomem            *regs;
	int                      irq;

	/* Driver-internal buffer list (buf_queue -> start_streaming hand-off) */
	struct list_head         buf_list;
	spinlock_t               buf_lock;

	/* Descriptor ring */
	struct vcam_hw_desc     *ring;
	struct vcam_buffer     **ring_bufs;
	u32                      ring_head;
	u32                      ring_tail;

	/* IRQ bottom-half */
	struct work_struct       irq_work;
	unsigned int             sequence;

	/* Controls */
	struct v4l2_ctrl_handler ctrl_handler;
};

/* ---- Controls ---- */

/*
 * vcam_s_ctrl -- Apply a control value to hardware
 *
 * Called when userspace writes a new control value via VIDIOC_S_CTRL
 * or an atomic commit.  The driver writes the value directly to the
 * hardware's image processing registers.
 *
 * In a real camera driver, this might:
 *   - Write to sensor registers via I2C (exposure, gain)
 *   - Write to ISP registers (white balance, sharpness)
 *   - Queue the change for the next frame (latched on vsync)
 *
 * The VCAM-2000 applies changes immediately -- the next frame
 * generated by the hardware will use the new values.
 */
static int vcam_s_ctrl(struct v4l2_ctrl *ctrl)
{
	struct vcam_device *vcam =
		container_of(ctrl->handler, struct vcam_device, ctrl_handler);

	switch (ctrl->id) {
	case V4L2_CID_BRIGHTNESS:
		/* Write brightness to hardware register */
		iowrite32(ctrl->val, vcam->regs + VCAM_BRIGHTNESS);
		pr_info(DRV_NAME ": brightness set to %d\n", ctrl->val);
		break;
	case V4L2_CID_HFLIP:
		/* Write hflip to hardware register */
		iowrite32(ctrl->val, vcam->regs + VCAM_HFLIP);
		pr_info(DRV_NAME ": hflip set to %d\n", ctrl->val);
		break;
	default:
		return -EINVAL;
	}
	return 0;
}

static const struct v4l2_ctrl_ops vcam_ctrl_ops = {
	.s_ctrl = vcam_s_ctrl,
};

/* ---- Descriptor ring helpers ---- */

static void vcam_submit_buffer(struct vcam_device *vcam,
			       struct vcam_buffer *buf)
{
	struct vcam_hw_desc *desc;
	void *vaddr;
	u32 head = vcam->ring_head;

	vaddr = vb2_plane_vaddr(&buf->vb.vb2_buf, 0);

	desc = &vcam->ring[head];
	desc->addr_lo = lower_32_bits((unsigned long)vaddr);
	desc->addr_hi = upper_32_bits((unsigned long)vaddr);
	desc->size    = vcam->fmt.sizeimage;
	desc->flags   = VCAM_DESC_OWN;

	vcam->ring_bufs[head] = buf;
	vcam->ring_head = (head + 1) % VCAM_RING_SIZE;

	iowrite32(vcam->ring_head, vcam->regs + VCAM_BUF_RING_HEAD);
}

/* ---- IRQ handler and bottom-half ---- */

static irqreturn_t vcam_isr(int irq, void *data)
{
	struct vcam_device *vcam = data;
	u32 status;

	status = ioread32(vcam->regs + VCAM_INT_STATUS);
	if (!status)
		return IRQ_NONE;

	iowrite32(status, vcam->regs + VCAM_INT_STATUS);

	if (status & VCAM_INT_FRAME_DONE)
		schedule_work(&vcam->irq_work);

	return IRQ_HANDLED;
}

static void vcam_irq_work(struct work_struct *work)
{
	struct vcam_device *vcam =
		container_of(work, struct vcam_device, irq_work);
	struct vcam_hw_desc *desc;
	struct vcam_buffer *buf;
	u32 hw_tail, tail;

	hw_tail = ioread32(vcam->regs + VCAM_BUF_RING_TAIL);
	tail = vcam->ring_tail;

	while (tail != hw_tail) {
		desc = &vcam->ring[tail];
		buf  = vcam->ring_bufs[tail];

		if (buf) {
			buf->vb.vb2_buf.timestamp = ktime_get_ns();
			buf->vb.sequence = vcam->sequence++;
			buf->vb.field = V4L2_FIELD_NONE;

			if (desc->flags & VCAM_DESC_ERROR)
				vb2_buffer_done(&buf->vb.vb2_buf,
						VB2_BUF_STATE_ERROR);
			else
				vb2_buffer_done(&buf->vb.vb2_buf,
						VB2_BUF_STATE_DONE);

			vcam->ring_bufs[tail] = NULL;
		}

		tail = (tail + 1) % VCAM_RING_SIZE;
	}

	vcam->ring_tail = tail;
}

/* ---- VB2 operations ---- */

static int vcam_queue_setup(struct vb2_queue *q,
			    unsigned int *num_buffers,
			    unsigned int *num_planes,
			    unsigned int sizes[], struct device *alloc_devs[])
{
	struct vcam_device *vcam = vb2_get_drv_priv(q);

	if (*num_buffers < 2)
		*num_buffers = 2;

	if (*num_planes)
		return sizes[0] < vcam->fmt.sizeimage ? -EINVAL : 0;

	*num_planes = 1;
	sizes[0] = vcam->fmt.sizeimage;
	return 0;
}

static int vcam_buf_prepare(struct vb2_buffer *vb)
{
	struct vcam_device *vcam = vb2_get_drv_priv(vb->vb2_queue);

	vb2_set_plane_payload(vb, 0, vcam->fmt.sizeimage);
	return 0;
}

static void vcam_buf_queue(struct vb2_buffer *vb)
{
	struct vcam_device *vcam = vb2_get_drv_priv(vb->vb2_queue);
	struct vcam_buffer *buf = container_of(to_vb2_v4l2_buffer(vb),
					       struct vcam_buffer, vb);
	unsigned long flags;

	spin_lock_irqsave(&vcam->buf_lock, flags);
	if (vcam->ring)
		vcam_submit_buffer(vcam, buf);
	else
		list_add_tail(&buf->list, &vcam->buf_list);
	spin_unlock_irqrestore(&vcam->buf_lock, flags);
}

static int vcam_start_streaming(struct vb2_queue *q, unsigned int count)
{
	struct vcam_device *vcam = vb2_get_drv_priv(q);
	struct vcam_buffer *buf, *tmp;
	unsigned long flags;
	int ret;

	vcam->ring_bufs = kcalloc(VCAM_RING_SIZE, sizeof(void *), GFP_KERNEL);
	if (!vcam->ring_bufs) {
		ret = -ENOMEM;
		goto err_return_bufs;
	}

	vcam->ring_head = 0;
	vcam->ring_tail = 0;
	vcam->sequence  = 0;

	vcam->ring = kcalloc(VCAM_RING_SIZE, sizeof(struct vcam_hw_desc),
			     GFP_KERNEL);
	if (!vcam->ring) {
		ret = -ENOMEM;
		goto err_free_bufs;
	}

	ret = vcam_hw_set_buf_ring(vcam->ring, VCAM_RING_SIZE);
	if (ret)
		goto err_free_ring;

	spin_lock_irqsave(&vcam->buf_lock, flags);
	list_for_each_entry_safe(buf, tmp, &vcam->buf_list, list) {
		list_del(&buf->list);
		vcam_submit_buffer(vcam, buf);
	}
	spin_unlock_irqrestore(&vcam->buf_lock, flags);

	/* Program format into hardware */
	iowrite32(vcam->fmt.width,        vcam->regs + VCAM_FMT_WIDTH);
	iowrite32(vcam->fmt.height,       vcam->regs + VCAM_FMT_HEIGHT);
	iowrite32(vcam->fmt.pixelformat,  vcam->regs + VCAM_FMT_PIXFMT);
	iowrite32(vcam->fmt.bytesperline, vcam->regs + VCAM_FMT_STRIDE);
	iowrite32(vcam->fmt.sizeimage,    vcam->regs + VCAM_FMT_FRAMESIZE);

	/* Unmask frame-done interrupt */
	iowrite32((u32)~VCAM_INT_FRAME_DONE, vcam->regs + VCAM_INT_MASK);

	/* Enable and start streaming */
	iowrite32(VCAM_CTRL_ENABLE | VCAM_CTRL_STREAM_ON |
		  VCAM_CTRL_RING_ENABLE, vcam->regs + VCAM_CTRL);
	vcam_hw_notify_ctrl();

	pr_info(DRV_NAME ": streaming started (%u buffers)\n", count);
	return 0;

err_free_ring:
	spin_lock_irqsave(&vcam->buf_lock, flags);
	kfree(vcam->ring);
	vcam->ring = NULL;
	spin_unlock_irqrestore(&vcam->buf_lock, flags);
err_free_bufs:
	kfree(vcam->ring_bufs);
	vcam->ring_bufs = NULL;
err_return_bufs:
	spin_lock_irqsave(&vcam->buf_lock, flags);
	list_for_each_entry_safe(buf, tmp, &vcam->buf_list, list) {
		list_del(&buf->list);
		vb2_buffer_done(&buf->vb.vb2_buf, VB2_BUF_STATE_QUEUED);
	}
	spin_unlock_irqrestore(&vcam->buf_lock, flags);
	return ret;
}

static void vcam_stop_streaming(struct vb2_queue *q)
{
	struct vcam_device *vcam = vb2_get_drv_priv(q);
	struct vcam_buffer *buf, *tmp;
	unsigned long flags;
	u32 i;

	iowrite32(0, vcam->regs + VCAM_CTRL);
	vcam_hw_notify_ctrl();
	iowrite32(0xFFFFFFFF, vcam->regs + VCAM_INT_MASK);

	cancel_work_sync(&vcam->irq_work);

	spin_lock_irqsave(&vcam->buf_lock, flags);
	for (i = 0; i < VCAM_RING_SIZE; i++) {
		buf = vcam->ring_bufs[i];
		if (buf) {
			vb2_buffer_done(&buf->vb.vb2_buf,
					VB2_BUF_STATE_ERROR);
			vcam->ring_bufs[i] = NULL;
		}
	}
	list_for_each_entry_safe(buf, tmp, &vcam->buf_list, list) {
		list_del(&buf->list);
		vb2_buffer_done(&buf->vb.vb2_buf, VB2_BUF_STATE_ERROR);
	}
	spin_unlock_irqrestore(&vcam->buf_lock, flags);

	vcam_hw_clear_buf_ring();
	kfree(vcam->ring_bufs);

	spin_lock_irqsave(&vcam->buf_lock, flags);
	kfree(vcam->ring);
	vcam->ring = NULL;
	spin_unlock_irqrestore(&vcam->buf_lock, flags);

	vcam->ring_bufs = NULL;

	pr_info(DRV_NAME ": streaming stopped\n");
}

static const struct vb2_ops vcam_vb2_ops = {
	.queue_setup     = vcam_queue_setup,
	.buf_prepare     = vcam_buf_prepare,
	.buf_queue       = vcam_buf_queue,
	.start_streaming = vcam_start_streaming,
	.stop_streaming  = vcam_stop_streaming,
	.wait_prepare    = vb2_ops_wait_prepare,
	.wait_finish     = vb2_ops_wait_finish,
};

/* ---- V4L2 ioctl operations ---- */

static int vcam_querycap(struct file *file, void *fh,
			 struct v4l2_capability *cap)
{
	strscpy(cap->driver, DRV_NAME, sizeof(cap->driver));
	strscpy(cap->card, "VCAM-2000 Controls", sizeof(cap->card));
	strscpy(cap->bus_info, "platform:vcam_ctrl", sizeof(cap->bus_info));
	return 0;
}

static int vcam_enum_fmt(struct file *file, void *fh,
			 struct v4l2_fmtdesc *f)
{
	if (f->index > 0)
		return -EINVAL;

	f->pixelformat = V4L2_PIX_FMT_RGB24;
	strscpy(f->description, "RGB24", sizeof(f->description));
	return 0;
}

static int vcam_g_fmt(struct file *file, void *fh,
		      struct v4l2_format *f)
{
	struct vcam_device *vcam = video_drvdata(file);

	f->fmt.pix = vcam->fmt;
	return 0;
}

static void vcam_clamp_format(struct v4l2_pix_format *pix)
{
	pix->width  = clamp_t(u32, pix->width,
			      VCAM_HW_MIN_WIDTH, VCAM_HW_MAX_WIDTH);
	pix->height = clamp_t(u32, pix->height,
			      VCAM_HW_MIN_HEIGHT, VCAM_HW_MAX_HEIGHT);
	pix->width  = round_down(pix->width, VCAM_HW_STEP);
	pix->height = round_down(pix->height, VCAM_HW_STEP);

	pix->pixelformat  = V4L2_PIX_FMT_RGB24;
	pix->field         = V4L2_FIELD_NONE;
	pix->bytesperline  = pix->width * 3;
	pix->sizeimage     = pix->bytesperline * pix->height;
	pix->colorspace    = V4L2_COLORSPACE_SRGB;
}

static int vcam_try_fmt(struct file *file, void *fh,
			struct v4l2_format *f)
{
	vcam_clamp_format(&f->fmt.pix);
	return 0;
}

static int vcam_s_fmt(struct file *file, void *fh,
		      struct v4l2_format *f)
{
	struct vcam_device *vcam = video_drvdata(file);

	if (vb2_is_busy(&vcam->queue))
		return -EBUSY;

	vcam_clamp_format(&f->fmt.pix);
	vcam->fmt = f->fmt.pix;
	pr_info(DRV_NAME ": format set to %ux%u RGB24\n",
		vcam->fmt.width, vcam->fmt.height);
	return 0;
}

static int vcam_enum_framesizes(struct file *file, void *fh,
				struct v4l2_frmsizeenum *fsize)
{
	if (fsize->index > 0)
		return -EINVAL;
	if (fsize->pixel_format != V4L2_PIX_FMT_RGB24)
		return -EINVAL;

	fsize->type = V4L2_FRMSIZE_TYPE_STEPWISE;
	fsize->stepwise.min_width   = VCAM_HW_MIN_WIDTH;
	fsize->stepwise.max_width   = VCAM_HW_MAX_WIDTH;
	fsize->stepwise.step_width  = VCAM_HW_STEP;
	fsize->stepwise.min_height  = VCAM_HW_MIN_HEIGHT;
	fsize->stepwise.max_height  = VCAM_HW_MAX_HEIGHT;
	fsize->stepwise.step_height = VCAM_HW_STEP;
	return 0;
}

static const struct v4l2_ioctl_ops vcam_ioctl_ops = {
	.vidioc_querycap         = vcam_querycap,
	.vidioc_enum_fmt_vid_cap = vcam_enum_fmt,
	.vidioc_g_fmt_vid_cap    = vcam_g_fmt,
	.vidioc_s_fmt_vid_cap    = vcam_s_fmt,
	.vidioc_try_fmt_vid_cap  = vcam_try_fmt,
	.vidioc_enum_framesizes  = vcam_enum_framesizes,
	/* VB2 helpers */
	.vidioc_reqbufs          = vb2_ioctl_reqbufs,
	.vidioc_querybuf         = vb2_ioctl_querybuf,
	.vidioc_qbuf             = vb2_ioctl_qbuf,
	.vidioc_dqbuf            = vb2_ioctl_dqbuf,
	.vidioc_streamon         = vb2_ioctl_streamon,
	.vidioc_streamoff        = vb2_ioctl_streamoff,
};

/* ---- File operations ---- */

static const struct v4l2_file_operations vcam_fops = {
	.owner   = THIS_MODULE,
	.open    = v4l2_fh_open,
	.release = vb2_fop_release,
	.mmap    = vb2_fop_mmap,
	.read    = vb2_fop_read,
	.poll    = vb2_fop_poll,
	.unlocked_ioctl = video_ioctl2,
};

/* ---- Platform driver ---- */

static int vcam_probe(struct platform_device *pdev)
{
	struct vcam_device *vcam;
	struct vb2_queue *q;
	struct video_device *vdev;
	u32 chip_id;
	int ret;

	vcam = devm_kzalloc(&pdev->dev, sizeof(*vcam), GFP_KERNEL);
	if (!vcam)
		return -ENOMEM;

	vcam->pdev = pdev;
	mutex_init(&vcam->lock);
	spin_lock_init(&vcam->buf_lock);
	INIT_LIST_HEAD(&vcam->buf_list);
	INIT_WORK(&vcam->irq_work, vcam_irq_work);

	/* Map hardware registers */
	vcam->regs = vcam_hw_map_regs();
	if (!vcam->regs) {
		dev_err(&pdev->dev, "failed to map hardware registers\n");
		return -ENODEV;
	}

	/* Verify hardware */
	chip_id = ioread32(vcam->regs + VCAM_CHIP_ID);
	if (chip_id != VCAM_HW_CHIP_ID_VAL) {
		dev_err(&pdev->dev, "unexpected chip ID: 0x%08x\n", chip_id);
		ret = -ENODEV;
		goto err_unmap;
	}

	/* Request IRQ */
	vcam->irq = vcam_hw_get_irq();
	if (vcam->irq < 0) {
		ret = vcam->irq;
		goto err_unmap;
	}
	ret = request_irq(vcam->irq, vcam_isr, 0, DRV_NAME, vcam);
	if (ret)
		goto err_unmap;

	/* Default format from hardware */
	vcam->fmt.width        = ioread32(vcam->regs + VCAM_FMT_WIDTH);
	vcam->fmt.height       = ioread32(vcam->regs + VCAM_FMT_HEIGHT);
	vcam->fmt.pixelformat  = V4L2_PIX_FMT_RGB24;
	vcam->fmt.field        = V4L2_FIELD_NONE;
	vcam->fmt.bytesperline = vcam->fmt.width * 3;
	vcam->fmt.sizeimage    = vcam->fmt.bytesperline * vcam->fmt.height;
	vcam->fmt.colorspace   = V4L2_COLORSPACE_SRGB;

	/* Register V4L2 device */
	ret = v4l2_device_register(&pdev->dev, &vcam->v4l2_dev);
	if (ret)
		goto err_irq;

	/* Setup controls */
	v4l2_ctrl_handler_init(&vcam->ctrl_handler, 2);
	v4l2_ctrl_new_std(&vcam->ctrl_handler, &vcam_ctrl_ops,
			  V4L2_CID_BRIGHTNESS, 0, 255, 1, 128);
	v4l2_ctrl_new_std(&vcam->ctrl_handler, &vcam_ctrl_ops,
			  V4L2_CID_HFLIP, 0, 1, 1, 0);
	if (vcam->ctrl_handler.error) {
		ret = vcam->ctrl_handler.error;
		goto err_ctrl;
	}
	vcam->v4l2_dev.ctrl_handler = &vcam->ctrl_handler;

	/* Setup VB2 queue */
	q = &vcam->queue;
	q->type             = V4L2_BUF_TYPE_VIDEO_CAPTURE;
	q->io_modes         = VB2_MMAP | VB2_READ;
	q->drv_priv         = vcam;
	q->buf_struct_size  = sizeof(struct vcam_buffer);
	q->ops              = &vcam_vb2_ops;
	q->mem_ops          = &vb2_vmalloc_memops;
	q->timestamp_flags  = V4L2_BUF_FLAG_TIMESTAMP_MONOTONIC;
	q->min_queued_buffers = 2;
	q->lock             = &vcam->lock;
	q->dev              = &pdev->dev;

	ret = vb2_queue_init(q);
	if (ret)
		goto err_ctrl;

	/* Setup video device */
	vdev = &vcam->vdev;
	strscpy(vdev->name, DRV_NAME, sizeof(vdev->name));
	vdev->release      = video_device_release_empty;
	vdev->fops         = &vcam_fops;
	vdev->ioctl_ops    = &vcam_ioctl_ops;
	vdev->v4l2_dev     = &vcam->v4l2_dev;
	vdev->queue        = &vcam->queue;
	vdev->lock         = &vcam->lock;
	vdev->ctrl_handler = &vcam->ctrl_handler;
	vdev->device_caps  = V4L2_CAP_VIDEO_CAPTURE | V4L2_CAP_STREAMING
			     | V4L2_CAP_READWRITE;
	vdev->vfl_type     = VFL_TYPE_VIDEO;

	video_set_drvdata(vdev, vcam);
	platform_set_drvdata(pdev, vcam);

	ret = video_register_device(vdev, VFL_TYPE_VIDEO, -1);
	if (ret)
		goto err_ctrl;

	pr_info(DRV_NAME ": registered as /dev/video%d\n", vdev->num);
	return 0;

err_ctrl:
	v4l2_ctrl_handler_free(&vcam->ctrl_handler);
	v4l2_device_unregister(&vcam->v4l2_dev);
err_irq:
	free_irq(vcam->irq, vcam);
err_unmap:
	vcam_hw_unmap_regs();
	return ret;
}

static void vcam_remove(struct platform_device *pdev)
{
	struct vcam_device *vcam = platform_get_drvdata(pdev);

	video_unregister_device(&vcam->vdev);
	v4l2_ctrl_handler_free(&vcam->ctrl_handler);
	v4l2_device_unregister(&vcam->v4l2_dev);
	free_irq(vcam->irq, vcam);
	vcam_hw_unmap_regs();
	pr_info(DRV_NAME ": device removed\n");
}

static struct platform_driver vcam_driver = {
	.probe  = vcam_probe,
	.remove = vcam_remove,
	.driver = {
		.name = VCAM_HW_DEV_NAME,
	},
};

module_platform_driver(vcam_driver);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Raghu Bharadwaj");
MODULE_DESCRIPTION("Part 6: V4L2 Capture Device with Controls");
